import json
import logging
from groq import Groq
from app.config import settings
from app.utils.prompts import AGENT_SYSTEM_PROMPT
from app.schemas.outreach_schema import ProcessedCompany
from app.tools.signal_harvester import tool_signal_harvester
from app.tools.research_analyst import tool_research_analyst
from app.tools.outreach_sender import tool_outreach_automated_sender

logger = logging.getLogger(__name__)

available_tools = {
    "tool_signal_harvester": tool_signal_harvester,
    "tool_research_analyst": tool_research_analyst,
    "tool_outreach_automated_sender": tool_outreach_automated_sender
}

tools_schema = [
    {
        "type": "function",
        "function": {
            "name": "tool_signal_harvester",
            "description": "Fetch live company signals using news and search.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string", "description": "The exact name of the company to harvest signals for."}
                },
                "required": ["company"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "tool_research_analyst",
            "description": "Analyze signals and ICP to generate an Account Brief.",
            "parameters": {
                "type": "object",
                "properties": {
                    "icp": {"type": "string", "description": "The original Ideal Customer Profile."},
                    "company": {"type": "string", "description": "The exact name of the company."},
                    "signals_data_json": {"type": "string", "description": "JSON string of signals captured by signal harvester."}
                },
                "required": ["icp", "company", "signals_data_json"]
            }
        }
    },
    {
        "type": "function",
        "function": {
            "name": "tool_outreach_automated_sender",
            "description": "Generate and send a personalized outreach email.",
            "parameters": {
                "type": "object",
                "properties": {
                    "company": {"type": "string", "description": "The exact name of the company."},
                    "account_brief": {"type": "string", "description": "The account brief generated by the research analyst."},
                    "signals_data_json": {"type": "string", "description": "JSON string of signals captured."},
                    "target_email": {"type": "string", "description": "Optional email address to send the outreach to."}
                },
                "required": ["company", "account_brief", "signals_data_json"]
            }
        }
    }
]

class OutreachAgent:
    @staticmethod
    def process_company(company: str, icp: str, target_email: str = None) -> ProcessedCompany:
        """
        Runs the 3-tool agentic loop for a specific target company.
        """
        result = ProcessedCompany(company=company)
        
        if not settings.GROQ_API_KEY:
            logger.error("No GROQ_API_KEY configured. Cannot process agent workflow.")
            return result
            
        try:
            client = Groq(api_key=settings.GROQ_API_KEY)
            
            prompt_text = f"Execute the Outreach sequence for the company: '{company}'. The governing ICP is: '{icp}'"
            if target_email:
                prompt_text += f"\n\nIMPORTANT: Use the exact target email '{target_email}' in the tool_outreach_automated_sender."
            
            messages = [
                {"role": "system", "content": AGENT_SYSTEM_PROMPT},
                {"role": "user", "content": prompt_text}
            ]
            
            iterations = 0
            while iterations < 10:
                iterations += 1
                
                response = client.chat.completions.create(
                    model="llama-3.3-70b-versatile",
                    messages=messages,
                    tools=tools_schema,
                    tool_choice="auto",
                )
                
                response_message = response.choices[0].message
                tool_calls = response_message.tool_calls
                messages.append(response_message)
                
                if tool_calls:
                    for tool_call in tool_calls:
                        fn_name = tool_call.function.name
                        logger.info(f"[{company}] Agent invoking: {fn_name}")
                        
                        try:
                            args = json.loads(tool_call.function.arguments)
                        except Exception as e:
                            logger.error(f"Failed to parse args for {fn_name}: {e}")
                            break
                            
                        if fn_name not in available_tools:
                            break
                            
                        # Execute Tool
                        tool_fn = available_tools[fn_name]
                        try:
                            tool_result = tool_fn(**args)
                            serializable_string_res = ""
                            
                            # Update State
                            if fn_name == "tool_signal_harvester":
                                result.signals = tool_result.signals
                                serializable_string_res = json.dumps(tool_result.model_dump())
                            elif fn_name == "tool_research_analyst":
                                result.research_brief = tool_result
                                serializable_string_res = tool_result
                            elif fn_name == "tool_outreach_automated_sender":
                                result.email_status = tool_result.email_status
                                serializable_string_res = json.dumps(tool_result.model_dump())
                                
                            messages.append({
                                "tool_call_id": tool_call.id,
                                "role": "tool",
                                "name": fn_name,
                                "content": serializable_string_res,
                            })
                            
                            # Force exit the agentic loop immediately once the email is sent 
                            # to prevent duplicate sends from hallucinated extra loops.
                            if fn_name == "tool_outreach_automated_sender":
                                logger.info(f"[{company}] Email sent successfully. Terminating agent loop.")
                                return result
                                
                        except Exception as e:
                            logger.error(f"Tool {fn_name} failed: {e}")
                            return result
                else:
                    logger.info(f"Agent finished workflow for {company}.")
                    break
                    
        except Exception as e:
            logger.error(f"Agent workflow error for {company}: {e}")
            
        return result
